export const UPDATE_REGISTRATION_FORM = 'UPDATE_REGISTRATION_FORM';
export const RESET_REGISTRATION_FORM = 'RESET_REGISTRATION_FORM';
export const SET_REGISTRATION_FORM_ERRORS = 'SET_REGISTRATION_FORM_ERRORS';

export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM';
export const RESET_LOGIN_FORM = 'RESET_LOGIN_FORM';
export const SET_LOGIN_FORM_ERRORS = 'SET_LOGIN_FORM_ERRORS';

export const ADD_BOOK = 'ADD_BOOK';
export const SET_BOOKS = 'SET_BOOKS';
export const UPDATE_BOOK_FORM = 'UPDATE_BOOK_FORM';
export const RESET_BOOK_FORM = 'RESET_BOOK_FORM';

export const SHOW_TOAST = 'SHOW_TOAST';
export const HIDE_TOAST = 'HIDE_TOAST';



